//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipReservations.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("フェリー予約システム")]
        public string SYS_AppName {
            get {
                return ((string)(this["SYS_AppName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.231")]
        public string DB_ServerName_Stage {
            get {
                return ((string)(this["DB_ServerName_Stage"]));
            }
            set {
                this["DB_ServerName_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.231")]
        public string DB_ServerName_Release {
            get {
                return ((string)(this["DB_ServerName_Release"]));
            }
            set {
                this["DB_ServerName_Release"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shipR")]
        public string DB_Schema_Dev {
            get {
                return ((string)(this["DB_Schema_Dev"]));
            }
            set {
                this["DB_Schema_Dev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inluser")]
        public string DB_UserID {
            get {
                return ((string)(this["DB_UserID"]));
            }
            set {
                this["DB_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("inl1926")]
        public string DB_Password {
            get {
                return ((string)(this["DB_Password"]));
            }
            set {
                this["DB_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("フェリー予約sys_Stage")]
        public string DB_Schema_Stage {
            get {
                return ((string)(this["DB_Schema_Stage"]));
            }
            set {
                this["DB_Schema_Stage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("フェリー予約sys_release")]
        public string DB_Schema_Release {
            get {
                return ((string)(this["DB_Schema_Release"]));
            }
            set {
                this["DB_Schema_Release"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2021/05/10")]
        public string APP_BuildVer {
            get {
                return ((string)(this["APP_BuildVer"]));
            }
            set {
                this["APP_BuildVer"] = value;
            }
        }
    }
}
